version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/server
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
volumes:
  pg_data: